### PR TITLE
Feat: Add optional parameters to ImapReceiver and SmtpSender

### PR DESCRIPTION
**Pull request by OsamaAlRashed**
Add optional parameters to the Create method in the ImapReceiver class and the SmtpSender class. The optional parameters allow injecting implementations of IImapClient and ISmtpClient, providing more flexibility in usage.

### CODE REVIEW

**Comment by OsamaAlRashed** [comment]
I was working on a project using the Mailkit library, and when I needed to receive emails in real-time, I came across your library. It turned out to be a great solution to my needs!

However, I encountered a new problem when trying to retrieve the MIME message for a newly received email. I was getting a 'Message not found' exception. After investigating, I realized that the issue stemmed from using a separate instance of ImapClient for MailKit and another instance for your library.

To resolve this problem, I made modifications to the code, adding an optional parameter that allows injecting an existing ImapClient instance. By using the same instance for both libraries, users can avoid encountering the 'Message not found' exception.

I believe this edit will greatly improve the user experience and streamline the integration between the two libraries. Please review and provide your feedback. Thank you!

**Review by danzuep — APPROVED** [review]
Excellent merge request! You only changed what you needed to and gave a great explanation, thanks. Those functions are getting too long but I can't really remove them now, so I'll add another fluent overload to make it simpler.

**Comment by danzuep** [comment]
> It turned out to be a great solution to my needs!
Thanks for letting me know! It's nice to hear the library is being used by others.

> I was getting a 'Message not found' exception. After investigating, I realized that the issue stemmed from using a separate instance of ImapClient for MailKit and another instance for your library.
I'd seen that as well, but I hadn't had time to test theories about why it was happening. I appreciate you spending the time to figure it out. I've been away for three weeks so I only saw this today.

> By using the same instance for both libraries, users can avoid encountering the 'Message not found' exception.
Excellent! Thank you 😁

**Comment by danzuep** [comment]
I've [published a preview package](https://www.nuget.org/packages/MailKitSimplified.Sender/2.4.8-tags-v2-4-8-delt0001) with your changes, please check it out and let me know if you have any other enhancements to offer 😄

**Comment by OsamaAlRashed** [comment]
Thanks for merging my PR :) 
I will check it, and looking forward to providing more help and improvements to this useful library.

**Comment by danzuep** [comment]
The changes you requested are now live, you can add the realease to an existing project:
```ps
cd ./MailKitSimplified/samples/ConsoleServiceExample
dotnet add package MailKitSimplified.Receiver --version 2.5.0
../MailKitSimplified.ConsoleServiceExample.sln
```

**Pull request merged**
